debug: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booksp?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: booksp
    password: 159491
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  application:
    name: booksp
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,classpath:/static/upload/

mybatis:
  mapper-locations: classpath:cn/booksp/blog/mapper/**/*.xml
  type-aliases-package: cn.booksp.blog.common.pojo

logging:
  file: booksp_cn.log
  path: logs
  level:
    web: debug
    org.springframework.boot.autoconfigure: ERROR

server:
  tomcat:
    uri-encoding: UTF-8












