spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booksp?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:cn.booksp.blog.dao/*.xml
  type-aliases-package: cn.booksp.blog.common.pojo
